Repository urbanopt/geojson-modelica-translator, pull requests merged in 2023-08, with the labels that each got.

#576 remove ground loads from system parameter
  geojson_modelica_translator/system_parameters/schema.json
  geojson_modelica_translator/system_parameters/time_series_template.json
  tests/model_connectors/data/system_params_ghe.json
  tests/model_connectors/data/system_params_ghe_2.json
  tests/system_parameters/data/system_params_ghe.json
  tests/system_parameters/data/system_params_ghe_invalid.json
Labels: tests

#573 test a new poetry gha
  .github/workflows/ci.yml
  poetry.lock
Labels: ignore-for-release

#574 Use `filNam` parameter for TEASER loads and add within parsing to PackageParser
  .cspell/custom-dictionary-workspace.txt
  .gitignore
  .pre-commit-config.yaml
  geojson_modelica_translator/model_connectors/energy_transfer_systems/cooling_indirect.py
  geojson_modelica_translator/model_connectors/energy_transfer_systems/heating_indirect.py
  geojson_modelica_translator/model_connectors/load_connectors/spawn.py
  geojson_modelica_translator/model_connectors/load_connectors/teaser.py
  geojson_modelica_translator/model_connectors/load_connectors/time_series.py
  geojson_modelica_translator/model_connectors/load_connectors/time_series_mft_ets_coupling.py
  geojson_modelica_translator/model_connectors/model_base.py
  geojson_modelica_translator/model_connectors/plants/borefield.py
  geojson_modelica_translator/model_connectors/plants/chp.py
  geojson_modelica_translator/model_connectors/plants/cooling_plant.py
  geojson_modelica_translator/modelica/package_parser.py
  poetry.lock
  pyproject.toml
  tests/modelica/test_package_parser.py
Labels: enhancement

#575 Add new `ModelicaProject` class
  .cspell/custom-dictionary-workspace.txt
  geojson_modelica_translator/modelica/modelica_project.py
  poetry.lock
  tests/modelica/data/packages/teaser_single/Districts/DistrictEnergySystem.mo
  tests/modelica/data/packages/teaser_single/Districts/package.mo
  tests/modelica/data/packages/teaser_single/Districts/package.order
  tests/modelica/data/packages/teaser_single/Loads/B5a6b99ec37f4de7f94020090/Floor.mo
  tests/modelica/data/packages/teaser_single/Loads/B5a6b99ec37f4de7f94020090/ICT.mo
  tests/modelica/data/packages/teaser_single/Loads/B5a6b99ec37f4de7f94020090/Meeting.mo
  tests/modelica/data/packages/teaser_single/Loads/B5a6b99ec37f4de7f94020090/Office.mo
  tests/modelica/data/packages/teaser_single/Loads/B5a6b99ec37f4de7f94020090/Restroom.mo
  tests/modelica/data/packages/teaser_single/Loads/B5a6b99ec37f4de7f94020090/Storage.mo
  tests/modelica/data/packages/teaser_single/Loads/B5a6b99ec37f4de7f94020090/building.mo
  tests/modelica/data/packages/teaser_single/Loads/B5a6b99ec37f4de7f94020090/coupling.mo
  tests/modelica/data/packages/teaser_single/Loads/B5a6b99ec37f4de7f94020090/package.mo
  tests/modelica/data/packages/teaser_single/Loads/B5a6b99ec37f4de7f94020090/package.order
  tests/modelica/data/packages/teaser_single/Loads/Resources/Data/B5a6b99ec37f4de7f94020090/InternalGains_Floor.txt
  tests/modelica/data/packages/teaser_single/Loads/Resources/Data/B5a6b99ec37f4de7f94020090/InternalGains_ICT.txt
  tests/modelica/data/packages/teaser_single/Loads/Resources/Data/B5a6b99ec37f4de7f94020090/InternalGains_Meeting.txt
  tests/modelica/data/packages/teaser_single/Loads/Resources/Data/B5a6b99ec37f4de7f94020090/InternalGains_Office.txt
  tests/modelica/data/packages/teaser_single/Loads/Resources/Data/B5a6b99ec37f4de7f94020090/InternalGains_Restroom.txt
  tests/modelica/data/packages/teaser_single/Loads/Resources/Data/B5a6b99ec37f4de7f94020090/InternalGains_Storage.txt
  tests/modelica/data/packages/teaser_single/Loads/Resources/Data/B5a6b99ec37f4de7f94020090/USA_IL_Chicago-OHare.Intl.AP.725300_TMY3.mos
  tests/modelica/data/packages/teaser_single/Loads/Resources/Scripts/B5a6b99ec37f4de7f94020090/Dymola/RunTeaserCouplingBuilding.mos
  tests/modelica/data/packages/teaser_single/Loads/package.mo
  tests/modelica/data/packages/teaser_single/Loads/package.order
  tests/modelica/data/packages/teaser_single/package.mo
  tests/modelica/data/packages/teaser_single/package.order
  tests/modelica/test_modelica_project.py
Labels: Feature

#577 Add Dymola runner
  .cspell.json
  .cspell/custom-dictionary-workspace.txt
  .github/workflows/ci.yml
  README.rst
  geojson_modelica_translator/modelica/GMT_Lib/DHC/DHC_5G_waste_heat_GHX.py
  geojson_modelica_translator/modelica/modelica_project.py
  geojson_modelica_translator/modelica/modelica_runner.py
  geojson_modelica_translator/modelica/package_parser.py
  geojson_modelica_translator/system_parameters/system_parameters.py
  poetry.lock
  pyproject.toml
  tests/GMT_Lib/test_gmt_lib_des.py
  tests/base_test_case.py
  tests/model_connectors/test_time_series_5g.py
  tests/modelica/test_csv_modelica.py
  tests/modelica/test_modelica_project.py
  tests/modelica/test_modelica_runner.py
Labels: enhancement
