Repository urbanopt/geojson-modelica-translator, pull requests merged in 2024-01, with the labels that each got.

#603 Implement a PyPI release workflow
  .github/workflows/pypi_release.yml
  pyproject.toml
Labels: enhancement

#592 Update documentation for version 0.6.0
  .cspell.json
  .github/ISSUE_TEMPLATE.md
  CHANGELOG.rst
  LICENSE.md
  docs/developer_resources.rst
  docs/getting_started.rst
  geojson_modelica_translator/model_connectors/couplings/coupling.py
  geojson_modelica_translator/model_connectors/couplings/diagram.py
  geojson_modelica_translator/system_parameters/system_parameters.py
Labels: documentation

#593 Support Python 3.12
  .github/workflows/ci.yml
  .github/workflows/pypi_release.yml
  .pre-commit-config.yaml
  geojson_modelica_translator/model_connectors/plants/borefield.py
  geojson_modelica_translator/model_connectors/plants/cooling_plant.py
  geojson_modelica_translator/modelica/GMT_Lib/DHC/DHC_5G_waste_heat_GHX.py
  geojson_modelica_translator/modelica/modelica_runner.py
  geojson_modelica_translator/system_parameters/system_parameters.py
  management/uo_des.py
  poetry.lock
  pyproject.toml
  tests/modelica/test_modelica_runner.py
Labels: enhancement

#610 Add district nominal pump head to system parameters file
  geojson_modelica_translator/model_connectors/networks/templates/NetworkDistributionPump_Instance.mopt
  geojson_modelica_translator/system_parameters/schema.json
  geojson_modelica_translator/system_parameters/time_series_microgrid_template.json
  geojson_modelica_translator/system_parameters/time_series_template.json
  management/data/baseline_sys_params.json
  tests/model_connectors/data/system_params_ghe.json
  tests/model_connectors/data/system_params_ghe_2.json
Labels: enhancement

#611 Use Ubuntu 20 and fix CHP model
  geojson_modelica_translator/model_connectors/plants/templates/HeatingPlantWithCHP.mot
  geojson_modelica_translator/modelica/GMT_Lib/DHC/DHC_5G_waste_heat_GHX.mot
  geojson_modelica_translator/modelica/GMT_Lib/DHC/DHC_5G_waste_heat_GHX.py
  geojson_modelica_translator/modelica/GMT_Lib/DHC/DHC_5G_waste_heat_GHX_variable.mot
  geojson_modelica_translator/modelica/GMT_Lib/DHC/DHC_5G_waste_heat_GHX_variable.py
  geojson_modelica_translator/modelica/lib/runner/Dockerfile
  geojson_modelica_translator/modelica/lib/runner/README.md
  geojson_modelica_translator/modelica/modelica_runner.py
  pyproject.toml
  tests/GMT_Lib/test_gmt_lib_des.py
  tests/model_connectors/test_chp_system.py
Labels: bug

#617 Update instructions for releasing documentation publicly
  .coveragerc
  docs/developer_resources.rst
  docs/getting_started.rst
Labels: documentation

#618 Rename new modelica models to clarify MBL version
  geojson_modelica_translator/model_connectors/plants/chp.py
  geojson_modelica_translator/model_connectors/plants/templates/Boiler_TParallel_v10.mo
  geojson_modelica_translator/model_connectors/plants/templates/CentralHeatingPlant.mo
  geojson_modelica_translator/model_connectors/plants/templates/HeatingPlantWithCHP.mot
  geojson_modelica_translator/model_connectors/plants/templates/PartialPlantParallel_v10.mo
  geojson_modelica_translator/modelica/lib/runner/README.md
Labels: documentation, enhancement
